#!/bin/bash

CMAKE_TARGET="$2"

arm-none-eabi-objdump -S -C ${OUT_FOLDER}/bin/${CMAKE_TARGET} > ${OUT_FOLDER}/bin/${CMAKE_TARGET}.asm

if [ "$1" = "bank1" ]; then
    BIN_FILE="${OUT_FOLDER}/bin/${CMAKE_TARGET}_bank1.bin"
    MP_FILE="${OUT_FOLDER}/bin/${CMAKE_TARGET}_bank1_MP.bin"
    TRACE_FILE="${OUT_FOLDER}/bin/${CMAKE_TARGET}_bank1.trace"
else
    BIN_FILE="${OUT_FOLDER}/bin/${CMAKE_TARGET}_bank0.bin"
    MP_FILE="${OUT_FOLDER}/bin/${CMAKE_TARGET}_bank0_MP.bin"
    TRACE_FILE="${OUT_FOLDER}/bin/${CMAKE_TARGET}_bank0.trace"
fi

arm-none-eabi-objcopy -O binary -S ${OUT_FOLDER}/bin/${CMAKE_TARGET} ${BIN_FILE} --remove-section=App.trace
arm-none-eabi-objcopy -O binary -S ${OUT_FOLDER}/bin/${CMAKE_TARGET} ${TRACE_FILE} --only-section=App.trace

chmod +x ${REALTEK_SDK_PATH}/tools/prepend_header/prepend_header
chmod +x ${REALTEK_SDK_PATH}/tools/md5/MD5

${REALTEK_SDK_PATH}/tools/prepend_header/prepend_header -t app_code -b 15 -p ${BIN_FILE} -m 1 -i ${OT_SRCDIR}/src/bee4/common/mp.ini -r ${REALTEK_SDK_PATH}/tools/keys/rtk_ecdsa.pem -a ${REALTEK_SDK_PATH}/tools/keys/key.json

${REALTEK_SDK_PATH}/tools/md5/MD5 ${MP_FILE}
